name: Bug Report
description: File a bug report
labels: [ "bug", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug 🐛!

        Please search open/closed issues before submitting. Someone might have had the similar problem before 😉!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue.
      placeholder: |
        When I ____, I expected ____ to happen but ____ happened instead.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to the page
      description: The link to the page where the issue occurs.
      placeholder: https://eth.blockscout.com
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Explain how to reproduce the issue in the development environment.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: input
    id: version
    attributes:
      label: App version
      description: The version of the front-end app you use. You can find it in the footer of the page.
      placeholder: v1.2.0
    validations:
      required: true

  - type: input
    id: browser
    # validations:
    #   required: true
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on? Please specify browser vendor and its version.
      placeholder: Google Chrome 111

  - type: dropdown
    id: operating-system
    # validations:
    #  required: true
    attributes:
      label: Operating system
      description: The operating system this issue occurred with.
      options:
        - macOS
        - Windows
        - Linux

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Use this section to provide any additional information you might have (e.g screenshots or screencasts).